steps:
  - label: ":hammer: Example Script"
    command: "script.sh"
    artifact_paths: "artifacts/*"
    agents:
      queue: "local"

notify:
  - pagerduty_change_event: "24b2749165a9430fd012f061676705c2"
